Step 1: Import Libraries

In [1]:
# Import Libraries
import numpy as np

Step 2: Create Synthetic Sales Data

Let's simulate 30 days of sales:

In [2]:
# Set random seed for repeatability
np.random.seed(42)

# Generate random sales amounts between $100 and $1000
sales = np.random.randint(100, 1000, size=30)

# Print sales data
print("Sales Data for 30 Days:")
print(sales)


Sales Data for 30 Days:
[202 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199 971
 763 230 761 408 869 443 591 513 905 485 291 376]


Step 3: Basic Sales Analysis

In [3]:
# Total Sales
total_sales = np.sum(sales)
print(f"Total Sales in the Month: ${total_sales}")


Total Sales in the Month: $14631


In [4]:
# Average Daily Sales
average_sales = np.mean(sales)
print(f"Average Daily Sales: ${average_sales:.2f}")

Average Daily Sales: $487.70


In [5]:
# Maximum Sales (Best-selling day)
max_sales = np.max(sales)
best_day = np.argmax(sales) + 1  # Add 1 because days start at 1
print(f"Best-Selling Day: Day {best_day} with sales of ${max_sales}")

Best-Selling Day: Day 18 with sales of $971


In [6]:
# Minimum Sales (Worst-selling day)
min_sales = np.min(sales)
worst_day = np.argmin(sales) + 1
print(f"Worst-Selling Day: Day {worst_day} with sales of ${min_sales}")


Worst-Selling Day: Day 8 with sales of $120


Step 4: Find Days with Above Average Sales

In [7]:
above_average_days = np.where(sales > average_sales)
print(f"Days with Above Average Sales: {above_average_days[0] + 1}")  # +1 because days start at 1

Days with Above Average Sales: [ 2  3  7  9 11 14 18 19 21 23 25 26 27]


In [8]:
# Sales on those days:
print("Sales on Above Average Days:")
print(sales[above_average_days])

Sales on Above Average Days:
[535 960 800 714 566 558 971 763 761 869 591 513 905]


Step 5: Group Sales into Weeks

In [9]:
# Reshape the 30 days into 5 weeks:
weekly_sales = sales.reshape(5, 6)  # 5 weeks, 6 days per week
print("Weekly Sales Data:")
print(weekly_sales)

Weekly Sales Data:
[[202 535 960 370 206 171]
 [800 120 714 221 566 314]
 [430 558 187 472 199 971]
 [763 230 761 408 869 443]
 [591 513 905 485 291 376]]


In [10]:
# Weekly totals:
week_totals = np.sum(weekly_sales, axis=1)
print("Total Sales per Week:")
print(week_totals)

Total Sales per Week:
[2444 2735 2817 3474 3161]


In [11]:
# Best week:
best_week = np.argmax(week_totals) + 1
print(f"Best Week: Week {best_week} with total sales of ${week_totals[best_week-1]}")

Best Week: Week 4 with total sales of $3474
