Step 1: Import Libraries

In [13]:
# Import Libraries
import numpy as np

* Imports the NumPy library as np, a standard alias.

* NumPy provides powerful tools for numerical computing and data manipulation.

Step 2: Create Synthetic Sales Data

Let's simulate 30 days of sales:

In [14]:
# Set random seed for repeatability
np.random.seed(42)

# Generate random sales amounts between $100 and $1000
sales = np.random.randint(100, 1000, size=30)

# Print sales data
print("Sales Data for 30 Days:")
print(sales)


Sales Data for 30 Days:
[202 535 960 370 206 171 800 120 714 221 566 314 430 558 187 472 199 971
 763 230 761 408 869 443 591 513 905 485 291 376]


* Sets a random seed to ensure the same random data is generated each time.

* Generates 30 random integers between 100 and 999, simulating daily sales amounts.

* Prints the sales data array.

Step 3: Basic Sales Analysis

In [15]:
# Total Sales
total_sales = np.sum(sales)
print(f"Total Sales in the Month: ${total_sales}")


Total Sales in the Month: $14631


* Sums all daily sales to find total monthly sales.

* Prints the total sales value.

In [16]:
# Average Daily Sales
average_sales = np.mean(sales)
print(f"Average Daily Sales: ${average_sales:.2f}")

Average Daily Sales: $487.70


* Computes the average sales per day.

* Prints the average formatted to two decimal places.

In [17]:
# Maximum Sales (Best-selling day)
max_sales = np.max(sales)
best_day = np.argmax(sales) + 1  # Add 1 because days start at 1
print(f"Best-Selling Day: Day {best_day} with sales of ${max_sales}")

Best-Selling Day: Day 18 with sales of $971


* Finds the highest sales value and its day.

* Adds 1 to convert zero-based index to human-friendly day number.

* Prints the best-selling day and amount.

In [18]:
# Minimum Sales (Worst-selling day)
min_sales = np.min(sales)
worst_day = np.argmin(sales) + 1
print(f"Worst-Selling Day: Day {worst_day} with sales of ${min_sales}")


Worst-Selling Day: Day 8 with sales of $120


* Finds the lowest sales value and its day.

* Prints the worst-selling day and amount.

Step 4: Find Days with Above Average Sales

In [19]:
above_average_days = np.where(sales > average_sales)
print(f"Days with Above Average Sales: {above_average_days[0] + 1}")  # +1 because days start at 1

Days with Above Average Sales: [ 2  3  7  9 11 14 18 19 21 23 25 26 27]


* Uses Boolean indexing to find days where sales exceeded average.

* Prints the list of those days, adjusted for human counting.

In [20]:
# Sales on those days:
print("Sales on Above Average Days:")
print(sales[above_average_days])

Sales on Above Average Days:
[535 960 800 714 566 558 971 763 761 869 591 513 905]


* Prints the sales amounts corresponding to above-average days.

Step 5: Group Sales into Weeks

In [21]:
# Reshape the 30 days into 5 weeks:
weekly_sales = sales.reshape(5, 6)  # 5 weeks, 6 days per week
print("Weekly Sales Data:")
print(weekly_sales)

Weekly Sales Data:
[[202 535 960 370 206 171]
 [800 120 714 221 566 314]
 [430 558 187 472 199 971]
 [763 230 761 408 869 443]
 [591 513 905 485 291 376]]


* Reshapes the 1D sales array into a 5x6 2D array (5 weeks, 6 days each).

* Prints the weekly sales breakdown.

In [22]:
# Weekly totals:
week_totals = np.sum(weekly_sales, axis=1)
print("Total Sales per Week:")
print(week_totals)

Total Sales per Week:
[2444 2735 2817 3474 3161]


* Sums sales across each week (rows) to get total sales per week.

* Prints the weekly totals.

In [23]:
# Best week:
best_week = np.argmax(week_totals) + 1
print(f"Best Week: Week {best_week} with total sales of ${week_totals[best_week-1]}")

Best Week: Week 4 with total sales of $3474


* Finds the week with the highest total sales.

* Prints the best week number and its total sales.